In [32]:
import torch
from torch.utils.data import DataLoader,Dataset
import pandas as pd
from sklearn.model_selection import train_test_split
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt


In [33]:
torch.manual_seed(42)

In [34]:

df=pd.read_excel("fmnist_small.xlsx")
df.head(5)

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      9       0       0       0       0       0       0       0       0   
1      7       0       0       0       0       0       0       0       0   
2      0       0       0       0       0       0       1       0       0   
3      8       0       0       0       0       0       0       0       0   
4      8       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         7         0        50       205       196   
1       0  ...         0         0         0         0         0         0   
2       0  ...       142       142       142        21         0         3   
3       0  ...         0         0         0         0         0         0   
4       0  ...       213       203       174       151       188        10   

   pixel781  pixel782  pixel783  pixel784  
0       213       165         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [35]:
x=df.iloc[:,1:].values
y=df.iloc[:,0].values

In [36]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ..., 16,  0,  0]])

In [37]:
y_train

array([7, 6, 7, ..., 0, 8, 6])

In [38]:
x_test

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  1,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ..., 51,  0,  0]])

In [39]:
y_test

array([7, 0, 5, ..., 7, 1, 2])

In [40]:
x_train=x_train/255.0
x_test=x_test/255.0

In [41]:
x_train

array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.0627451, 0.       ,
        0.       ]])

In [42]:
class custom(Dataset):
  def __init__(self,features,labels):
    self.features=torch.tensor(features,dtype=torch.float32)
    self.labels=torch.tensor(labels,dtype=torch.long)
  def __len__(self):
    return len(self.features)
  def __getitem__(self,index):
    return self.features[index],self.labels[index]

In [43]:
train_dataset=custom(x_train,y_train)


In [44]:
train_dataset[0]

(tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0

In [45]:
test_dataset=custom(x_test,y_test)

In [46]:
test_dataset

In [47]:
train=DataLoader(train_dataset,batch_size=32,shuffle=True)
test=DataLoader(test_dataset,batch_size=32,shuffle=False)

In [48]:
class mynn(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.model=nn.Sequential(
        nn.Linear(num_features,128),
        nn.ReLU(),
        nn.Linear(128,64),
        nn.ReLU(),
        nn.Linear(64,10)

    )
  def forward(self,x):
    return self.model(x)

In [58]:
epochs=1000
learning_rate=0.1

In [61]:
model=mynn(x_train.shape[1])
criterion=nn.CrossEntropyLoss()
optimiser=optim.SGD(model.parameters(),lr=learning_rate)

In [62]:
for epoch in range(epochs):
  total_loss=0
  for batch_features,batch_labels in train:
    output= model(batch_features)
    loss=criterion(output,batch_labels)
    optimiser.zero_grad()
    loss.backward()
    optimiser.step()
    total_loss+=loss.item()

  print(f"epoch;{epoch+1},Loss:{total_loss/len(train)}")



epoch;1,Loss:1.3392698657512665
epoch;2,Loss:0.7832989821831385
epoch;3,Loss:0.6584782379865647
epoch;4,Loss:0.5884015969435374
epoch;5,Loss:0.5376970623930295
epoch;6,Loss:0.4984269427259763
epoch;7,Loss:0.4691421795884768
epoch;8,Loss:0.4457626957694689
epoch;9,Loss:0.41080283363660175
epoch;10,Loss:0.3998829037944476
epoch;11,Loss:0.3739268133044243
epoch;12,Loss:0.37008025621374446
epoch;13,Loss:0.3404456977546215
epoch;14,Loss:0.3231501675148805
epoch;15,Loss:0.3239694624642531
epoch;16,Loss:0.29902341147263845
epoch;17,Loss:0.30323817061881225
epoch;18,Loss:0.2801922163863977
epoch;19,Loss:0.27895270576079684
epoch;20,Loss:0.25598083580533665
epoch;21,Loss:0.26413942463696005
epoch;22,Loss:0.24541014097630978
epoch;23,Loss:0.2366962600002686
epoch;24,Loss:0.23551451039810975
epoch;25,Loss:0.22005605151255925
epoch;26,Loss:0.20313507601618766
epoch;27,Loss:0.2057994557917118
epoch;28,Loss:0.19412941448390483
epoch;29,Loss:0.19506897990902264
epoch;30,Loss:0.18948864869773388
epoch

In [63]:
model.eval()

mynn(
  (model): Sequential(
    (0): Linear(in_features=784, out_features=128, bias=True)
    (1): ReLU()
    (2): Linear(in_features=128, out_features=64, bias=True)
    (3): ReLU()
    (4): Linear(in_features=64, out_features=10, bias=True)
  )
)

In [64]:
total=0
correct=0
with torch.no_grad():
  for batch_features,batch_labels in test:
    output= model(batch_features)
    _, predicted=torch.max(output,1)
    total=total+batch_labels.shape[0]
    correct+=(predicted==batch_labels).sum().item()
print(correct)
print("Accuracy:", correct / total)


1009
Accuracy: 0.8408333333333333
