In [14]:
import torch
from torch.utils.data import DataLoader,Dataset
import pandas as pd
from sklearn.model_selection import train_test_split
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt


In [15]:
torch.manual_seed(42)

In [16]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [17]:

df=pd.read_excel("fmnist_small.xlsx")
df.head(5)

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      9       0       0       0       0       0       0       0       0   
1      7       0       0       0       0       0       0       0       0   
2      0       0       0       0       0       0       1       0       0   
3      8       0       0       0       0       0       0       0       0   
4      8       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         7         0        50       205       196   
1       0  ...         0         0         0         0         0         0   
2       0  ...       142       142       142        21         0         3   
3       0  ...         0         0         0         0         0         0   
4       0  ...       213       203       174       151       188        10   

   pixel781  pixel782  pixel783  pixel784  
0       213       165         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [18]:
x=df.iloc[:,1:].values
y=df.iloc[:,0].values

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ..., 16,  0,  0]])

In [20]:
y_train

array([7, 6, 7, ..., 0, 8, 6])

In [21]:
x_test

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  1,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ..., 51,  0,  0]])

In [22]:
y_test

array([7, 0, 5, ..., 7, 1, 2])

In [23]:
x_train=x_train/255.0
x_test=x_test/255.0

In [24]:
x_train

array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.0627451, 0.       ,
        0.       ]])

In [25]:
class custom(Dataset):
  def __init__(self,features,labels):
    self.features=torch.tensor(features,dtype=torch.float32)
    self.labels=torch.tensor(labels,dtype=torch.long)
  def __len__(self):
    return len(self.features)
  def __getitem__(self,index):
    return self.features[index],self.labels[index]

In [26]:
train_dataset=custom(x_train,y_train)


In [27]:
train_dataset[0]

(tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0

In [28]:
test_dataset=custom(x_test,y_test)

In [29]:
test_dataset

In [30]:
train=DataLoader(train_dataset,batch_size=32,shuffle=True,pin_memory=True)
test=DataLoader(test_dataset,batch_size=32,shuffle=False,pin_memory=True)

In [31]:
class mynn(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.model=nn.Sequential(
        nn.Linear(num_features,128),
        nn.ReLU(),
        nn.Linear(128,64),
        nn.ReLU(),
        nn.Linear(64,10)

    )
  def forward(self,x):
    return self.model(x)

In [32]:
epochs=100
learning_rate=0.1

In [34]:
model=mynn(x_train.shape[1])
model.to(device)
criterion=nn.CrossEntropyLoss()
optimiser=optim.SGD(model.parameters(),lr=learning_rate)

In [35]:
for epoch in range(epochs):
  total_loss=0
  for batch_features,batch_labels in train:
    batch_features,batch_labels=batch_features.to(device),batch_labels.to(device)
    output= model(batch_features)
    loss=criterion(output,batch_labels)
    optimiser.zero_grad()
    loss.backward()
    optimiser.step()
    total_loss+=loss.item()

  print(f"epoch;{epoch+1},Loss:{total_loss/len(train)}")



epoch;1,Loss:1.3521236288547516
epoch;2,Loss:0.8064551085233689
epoch;3,Loss:0.6735462007919947
epoch;4,Loss:0.5915317239363989
epoch;5,Loss:0.5425307923555374
epoch;6,Loss:0.5055501459042231
epoch;7,Loss:0.47644907822211585
epoch;8,Loss:0.4658418587843577
epoch;9,Loss:0.4384323724110921
epoch;10,Loss:0.4127937444051107
epoch;11,Loss:0.39807319313287737
epoch;12,Loss:0.3713326790928841
epoch;13,Loss:0.36183315366506574
epoch;14,Loss:0.3469938766956329
epoch;15,Loss:0.34035046994686124
epoch;16,Loss:0.3084445019563039
epoch;17,Loss:0.3025454026460648
epoch;18,Loss:0.30051081771651905
epoch;19,Loss:0.2800697274506092
epoch;20,Loss:0.27594346282382803
epoch;21,Loss:0.26984709764520326
epoch;22,Loss:0.25902099629243214
epoch;23,Loss:0.24530831654866536
epoch;24,Loss:0.258346579571565
epoch;25,Loss:0.2352633067468802
epoch;26,Loss:0.21670722492039204
epoch;27,Loss:0.21722820882995925
epoch;28,Loss:0.20795285845796266
epoch;29,Loss:0.20976067639887333
epoch;30,Loss:0.20667426104346912
epoch;

In [36]:
model.eval()

mynn(
  (model): Sequential(
    (0): Linear(in_features=784, out_features=128, bias=True)
    (1): ReLU()
    (2): Linear(in_features=128, out_features=64, bias=True)
    (3): ReLU()
    (4): Linear(in_features=64, out_features=10, bias=True)
  )
)

In [37]:
total=0
correct=0
with torch.no_grad():
  for batch_features,batch_labels in test:
    batch_features,batch_labels=batch_features.to(device),batch_labels.to(device)
    output= model(batch_features)
    _, predicted=torch.max(output,1)
    total=total+batch_labels.shape[0]
    correct+=(predicted==batch_labels).sum().item()
print(correct)
print("Accuracy:", correct / total)


1007
Accuracy: 0.8391666666666666
