In [118]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [119]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [120]:
df.shape

(569, 33)

In [121]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [122]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)


In [123]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [124]:
X_train

array([[-0.52513221, -0.79972011, -0.54599733, ..., -1.00951628,
        -0.66956861, -1.20807717],
       [-0.37388377,  0.69382691, -0.28058681, ...,  1.25441107,
         0.86392047,  2.40348855],
       [-1.84042291,  1.41621123, -1.80453025, ..., -0.98151049,
        -0.15895819,  1.35964934],
       ...,
       [-0.627867  ,  0.32915057, -0.58562316, ...,  0.01004579,
        -0.69775165,  0.9592161 ],
       [ 0.91600861,  0.86338979,  0.7818808 , ..., -0.49178766,
        -0.71930339, -1.08482158],
       [ 0.83325003,  0.38489727,  0.81490232, ...,  1.02733711,
        -0.43581514, -0.44554378]])

In [125]:
y_train

189    B
229    M
539    B
234    B
364    B
      ..
337    M
481    B
286    B
261    M
335    M
Name: diagnosis, Length: 455, dtype: object

In [126]:
X_test

array([[-0.75628549, -1.10400419, -0.74577757, ..., -0.6134993 ,
         0.09137354,  0.48683463],
       [-0.64213572, -0.23063921, -0.60832546, ..., -0.01568926,
         0.84734221,  0.0061968 ],
       [-0.83904407,  2.32906345, -0.8828169 , ..., -1.73842369,
        -2.18813725, -1.44456278],
       ...,
       [ 0.59924301, -0.13308248,  0.6910716 , ...,  0.88352361,
        -0.19211471,  1.34195715],
       [-0.27971021,  0.27804943, -0.3301191 , ..., -1.10337352,
        -0.32971427, -0.54579953],
       [-0.50800974,  0.57071961, -0.50678427, ...,  0.0857371 ,
         0.14276615,  0.53460354]])

In [127]:
y_test

478    B
216    B
561    B
546    B
365    M
      ..
292    B
555    B
283    M
494    B
88     B
Name: diagnosis, Length: 114, dtype: object

In [128]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [129]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,

In [130]:
y_test

array([0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0])

In [131]:
x_train_tensor=torch.from_numpy(X_train)
x_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [132]:
x_train_tensor.shape,x_test_tensor.shape,y_train_tensor.shape,y_test_tensor.shape

(torch.Size([455, 30]),
 torch.Size([114, 30]),
 torch.Size([455]),
 torch.Size([114]))

In [133]:
class MyNN():
  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)
  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred
  def loss_function(self,y_pred,y):
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)
    loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)+torch.log(1-y_pred)).mean()
    return loss

In [134]:
learning_rate=0.1
epochs=1000

In [135]:
model=MyNN(x_train_tensor)
for epoch in range(epochs):
  y_pred=model.forward(x_train_tensor)
  loss=model.loss_function(y_pred,y_train_tensor)
  loss.backward()
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad
  model.weights.grad.zero_()
  model.bias.grad.zero_()
  print("epoch",{epoch+1},"loss",{loss})


epoch {1} loss {tensor(4.8999, dtype=torch.float64, grad_fn=<NegBackward0>)}
epoch {2} loss {tensor(4.7062, dtype=torch.float64, grad_fn=<NegBackward0>)}
epoch {3} loss {tensor(4.4849, dtype=torch.float64, grad_fn=<NegBackward0>)}
epoch {4} loss {tensor(4.2495, dtype=torch.float64, grad_fn=<NegBackward0>)}
epoch {5} loss {tensor(4.0012, dtype=torch.float64, grad_fn=<NegBackward0>)}
epoch {6} loss {tensor(3.7319, dtype=torch.float64, grad_fn=<NegBackward0>)}
epoch {7} loss {tensor(3.4573, dtype=torch.float64, grad_fn=<NegBackward0>)}
epoch {8} loss {tensor(3.1642, dtype=torch.float64, grad_fn=<NegBackward0>)}
epoch {9} loss {tensor(2.8668, dtype=torch.float64, grad_fn=<NegBackward0>)}
epoch {10} loss {tensor(2.5648, dtype=torch.float64, grad_fn=<NegBackward0>)}
epoch {11} loss {tensor(2.2569, dtype=torch.float64, grad_fn=<NegBackward0>)}
epoch {12} loss {tensor(1.9305, dtype=torch.float64, grad_fn=<NegBackward0>)}
epoch {13} loss {tensor(1.6205, dtype=torch.float64, grad_fn=<NegBackward

In [136]:
model.weights

tensor([[ 0.0194],
        [ 0.0221],
        [ 0.2076],
        [ 0.0266],
        [ 0.0033],
        [-0.0429],
        [-0.0155],
        [-0.1661],
        [-0.0091],
        [ 0.1173],
        [-0.0103],
        [ 0.0191],
        [-0.1275],
        [ 0.2062],
        [ 0.0204],
        [-0.1562],
        [-0.0124],
        [ 0.0249],
        [-0.0032],
        [ 0.0887],
        [-0.3059],
        [-0.0219],
        [ 0.2335],
        [-0.1505],
        [-0.0130],
        [ 0.2021],
        [ 0.0125],
        [ 0.0688],
        [ 0.0160],
        [-0.1512]], dtype=torch.float64, requires_grad=True)

In [137]:
model.bias

tensor([-0.9687], dtype=torch.float64, requires_grad=True)

In [140]:
with torch.no_grad():
  y_pred=model.forward(x_test_tensor)
  y_pred=(y_pred>0.8).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f"Accuracy:{accuracy.item()}")


Accuracy:0.6578947305679321
