In [205]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [206]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [207]:
df.shape

(569, 33)

In [208]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [209]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)


In [210]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [211]:
X_train

array([[ 1.91867184,  2.80434905,  1.85465504, ...,  0.79010844,
        -0.06532402, -0.10428922],
       [-0.48022802, -0.68432773, -0.47029498, ..., -0.48715688,
         0.38863461, -0.47519232],
       [-0.4743699 , -0.03609387, -0.44168678, ..., -0.35379283,
        -1.24688185, -0.66609832],
       ...,
       [-0.19610924, -0.07852372, -0.17780815, ...,  0.46841061,
        -0.38483497, -0.39446635],
       [-0.5036605 ,  1.13544151, -0.35415422, ...,  1.65057205,
         2.30411859,  6.73123663],
       [ 1.09853514,  1.23915893,  0.9793295 , ..., -0.02662926,
        -0.64107643, -0.25155957]])

In [212]:
y_train

265    M
502    B
355    B
309    B
129    M
      ..
295    B
200    B
396    B
9      M
274    M
Name: diagnosis, Length: 455, dtype: object

In [213]:
X_test

array([[ 1.5730428 ,  2.25040375,  1.76498754, ...,  1.2304909 ,
        -0.14441089,  0.89496735],
       [ 0.43363859,  0.93743553,  0.76583547, ...,  2.04410531,
         0.58160658,  0.97132975],
       [-0.97231005,  0.53199472, -1.01427777, ..., -1.80065224,
        -0.71383635, -0.99118397],
       ...,
       [-1.2007767 , -0.96955063, -1.2170971 , ..., -1.63792935,
         0.03748891, -0.38846645],
       [ 0.11730015, -1.31134667,  0.08649746, ..., -0.36612978,
        -0.44810446, -0.74246072],
       [-0.74970151, -0.24588592, -0.67823817, ...,  0.41062993,
        -0.39432539,  0.46951968]])

In [214]:
y_test

256    M
258    M
550    B
457    B
136    B
      ..
463    B
386    B
185    B
513    B
469    B
Name: diagnosis, Length: 114, dtype: object

In [215]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [216]:
y_train

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,

In [217]:
y_test

array([1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [218]:
x_train_tensor=torch.from_numpy(X_train)
x_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [219]:
x_train_tensor.shape,x_test_tensor.shape,y_train_tensor.shape,y_test_tensor.shape

(torch.Size([455, 30]),
 torch.Size([114, 30]),
 torch.Size([455]),
 torch.Size([114]))

In [220]:
import torch.nn as nn
class MyNN(nn.Module):
  def __init__(self,num_features):
   super().__init__()
   self.linear=nn.Linear(num_features,1)
   self.sigmoid=nn.Sigmoid()
  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out


In [221]:
learning_rate=0.1
epochs=1000

In [222]:
loss_function=nn.BCELoss()

In [223]:
print(x_train_tensor.shape)


torch.Size([455, 30])


In [224]:
x_train_tensor = x_train_tensor.double()
y_train_tensor = y_train_tensor.double()
model=MyNN(x_train_tensor.shape[1]).double()
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
for epoch in range(epochs):
  y_pred=model(x_train_tensor)
  loss=loss_function(y_pred,y_train_tensor.view(-1,1))
  loss.backward()
  optimizer.zero_grad()
  optimizer.step()

  print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")



Epoch 1, Loss: 0.5602
Epoch 2, Loss: 0.5602
Epoch 3, Loss: 0.5602
Epoch 4, Loss: 0.5602
Epoch 5, Loss: 0.5602
Epoch 6, Loss: 0.5602
Epoch 7, Loss: 0.5602
Epoch 8, Loss: 0.5602
Epoch 9, Loss: 0.5602
Epoch 10, Loss: 0.5602
Epoch 11, Loss: 0.5602
Epoch 12, Loss: 0.5602
Epoch 13, Loss: 0.5602
Epoch 14, Loss: 0.5602
Epoch 15, Loss: 0.5602
Epoch 16, Loss: 0.5602
Epoch 17, Loss: 0.5602
Epoch 18, Loss: 0.5602
Epoch 19, Loss: 0.5602
Epoch 20, Loss: 0.5602
Epoch 21, Loss: 0.5602
Epoch 22, Loss: 0.5602
Epoch 23, Loss: 0.5602
Epoch 24, Loss: 0.5602
Epoch 25, Loss: 0.5602
Epoch 26, Loss: 0.5602
Epoch 27, Loss: 0.5602
Epoch 28, Loss: 0.5602
Epoch 29, Loss: 0.5602
Epoch 30, Loss: 0.5602
Epoch 31, Loss: 0.5602
Epoch 32, Loss: 0.5602
Epoch 33, Loss: 0.5602
Epoch 34, Loss: 0.5602
Epoch 35, Loss: 0.5602
Epoch 36, Loss: 0.5602
Epoch 37, Loss: 0.5602
Epoch 38, Loss: 0.5602
Epoch 39, Loss: 0.5602
Epoch 40, Loss: 0.5602
Epoch 41, Loss: 0.5602
Epoch 42, Loss: 0.5602
Epoch 43, Loss: 0.5602
Epoch 44, Loss: 0.56

In [230]:
with torch.no_grad():
  y_pred=model.forward(x_test_tensor)
  y_pred=(y_pred>0.8).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f"Accuracy:{accuracy.item()}")


Accuracy:0.6549707651138306
