In [1]:
import torch
print(torch.__version__)

2.9.0+cu126


In [3]:
if torch.cuda.is_available():
  print("GPU is available")
  print("Using GPU:",torch.cuda.get_device_name(0))
else:
  print("Using CPU")

GPU is available
Using GPU: Tesla T4


# Creating Tensors

In [6]:
a=torch.empty(2,3)
# IT allocates memory and shows the value of it
a,type(a)

(tensor([[9.4601e-04, 4.5488e-41, 2.5807e-26],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]),
 torch.Tensor)

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.rand(2,3)

tensor([[0.8516, 0.3846, 0.1701],
        [0.8399, 0.0874, 0.8438]])

In [14]:
torch.manual_seed(100)
torch.rand(2,3)
#for Fixed trainable weights


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
torch.tensor([
    [1,2,3],
    [1,2,3]]
)

tensor([[1, 2, 3],
        [1, 2, 3]])

In [17]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [19]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [20]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [21]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# Tensor Shapes

In [23]:
a=torch.empty(2,3)
a.shape

torch.Size([2, 3])

# Create same shape Tensors

In [24]:
torch.empty_like(a)


tensor([[1.3563e-19, 2.9503e-39, 1.3593e-43],
        [0.0000e+00, 2.9092e-26, 0.0000e+00]])

In [27]:
torch.zeros_like(a),torch.ones_like(a)

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

In [32]:
torch.rand_like(a,dtype=torch.float32)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

# Tensor Data Types

In [28]:
a.dtype

torch.float32

In [29]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [30]:
a.to(torch.float32)

tensor([[2.9092e-26, 0.0000e+00, 2.8141e-26],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Some mathematical operations

## Scalar

In [34]:
x=torch.rand(2,3)
x+2

tensor([[2.2239, 2.3023, 2.1784],
        [2.8238, 2.5557, 2.9770]])

In [35]:
x-2

tensor([[-1.7761, -1.6977, -1.8216],
        [-1.1762, -1.4443, -1.0230]])

In [36]:
x*2

tensor([[0.4478, 0.6047, 0.3568],
        [1.6477, 1.1115, 1.9540]])

In [37]:
x/2

tensor([[0.1119, 0.1512, 0.0892],
        [0.4119, 0.2779, 0.4885]])

In [38]:
(x*100)//3

tensor([[ 7., 10.,  5.],
        [27., 18., 32.]])

In [39]:
((x*100)//3)%2

tensor([[1., 0., 1.],
        [1., 0., 0.]])

In [40]:
x**2

tensor([[0.0501, 0.0914, 0.0318],
        [0.6787, 0.3089, 0.9546]])

## Element wise operation

In [42]:
a=torch.rand(2,3)
b=torch.rand(2,3)
a+b

tensor([[1.6012, 1.0494, 0.4811],
        [1.4163, 0.5609, 0.5482]])

In [43]:
a-b

tensor([[ 0.3059,  0.3634, -0.1554],
        [ 0.3641,  0.4716, -0.4765]])

In [44]:
a*b

tensor([[0.6175, 0.2423, 0.0518],
        [0.4683, 0.0231, 0.0184]])

In [45]:
a/b

tensor([[ 1.4723,  2.0593,  0.5118],
        [ 1.6921, 11.5604,  0.0700]])

In [46]:
a**b,a%b

(tensor([[0.9697, 0.8876, 0.5613],
         [0.9406, 0.9709, 0.1818]]),
 tensor([[0.3059, 0.0204, 0.1629],
         [0.3641, 0.0250, 0.0359]]))

In [48]:
torch.abs(a),torch.neg(a),torch.round(b),torch.ceil(a),torch.floor(b),torch.clamp(a,min=2,max=3)

(tensor([[0.9535, 0.7064, 0.1629],
         [0.8902, 0.5163, 0.0359]]),
 tensor([[-0.9535, -0.7064, -0.1629],
         [-0.8902, -0.5163, -0.0359]]),
 tensor([[1., 0., 0.],
         [1., 0., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[2., 2., 2.],
         [2., 2., 2.]]))

## Reduction

In [49]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 9., 7.],
        [9., 2., 6.]])

In [54]:
torch.sum(e),torch.sum(e,dim=0),torch.sum(e,dim=1),torch.mean(e),torch.median(e),torch.max(e),torch.min(e),torch.prod(e),torch.var(e),torch.std(e),torch.argmax(e),torch.argmin(e)

(tensor(41.),
 tensor([17., 11., 13.]),
 tensor([24., 17.]),
 tensor(6.8333),
 tensor(7.),
 tensor(9.),
 tensor(2.),
 tensor(54432.),
 tensor(6.9667),
 tensor(2.6394),
 tensor(1),
 tensor(4))

## Matrix operation

In [67]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[3, 1, 0],
        [2, 1, 2]])
tensor([[7, 9],
        [2, 4],
        [6, 6]])


In [68]:
torch.matmul(f,g)

tensor([[23, 31],
        [28, 34]])

In [69]:
torch.transpose(f,0,1)

tensor([[3, 2],
        [1, 1],
        [0, 2]])

## comparison

In [73]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)
i > j,i != j,i<j,i==j

tensor([[8, 4, 9],
        [0, 7, 9]])
tensor([[2, 7, 0],
        [2, 4, 4]])


(tensor([[ True, False,  True],
         [False,  True,  True]]),
 tensor([[True, True, True],
         [True, True, True]]),
 tensor([[False,  True, False],
         [ True, False, False]]),
 tensor([[False, False, False],
         [False, False, False]]))

## Special

In [74]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[6., 2., 1.],
        [0., 5., 1.]])

In [75]:
torch.log(k)

tensor([[1.7918, 0.6931, 0.0000],
        [  -inf, 1.6094, 0.0000]])

In [76]:
torch.exp(k)

tensor([[403.4288,   7.3891,   2.7183],
        [  1.0000, 148.4132,   2.7183]])

In [77]:
torch.sqrt(k)

tensor([[2.4495, 1.4142, 1.0000],
        [0.0000, 2.2361, 1.0000]])

In [78]:
torch.sigmoid(k)

tensor([[0.9975, 0.8808, 0.7311],
        [0.5000, 0.9933, 0.7311]])

In [79]:
torch.softmax(k,dim=-1)

tensor([[0.9756, 0.0179, 0.0066],
        [0.0066, 0.9756, 0.0179]])

In [80]:
torch.relu(k)

tensor([[6., 2., 1.],
        [0., 5., 1.]])

# Inplace operation

In [81]:
m = torch.rand(2,3)
n = torch.rand(2,3)
# Just place underscore
print(m)
print(n)

tensor([[0.3124, 0.9431, 0.8519],
        [0.9815, 0.1132, 0.4783]])
tensor([[0.4436, 0.3847, 0.4521],
        [0.5569, 0.9952, 0.0015]])


In [82]:
m.relu_()

tensor([[0.3124, 0.9431, 0.8519],
        [0.9815, 0.1132, 0.4783]])

In [84]:
m.add_(n)

tensor([[0.7560, 1.3279, 1.3039],
        [1.5384, 1.1084, 0.4798]])

## Copying a Tensor

In [85]:
a = torch.rand(2,3)
a

tensor([[0.0813, 0.4907, 0.2130],
        [0.4603, 0.1386, 0.0277]])

In [87]:
b=a
b

tensor([[0.0813, 0.4907, 0.2130],
        [0.4603, 0.1386, 0.0277]])

In [89]:
a[0][0]=0
a

tensor([[0.0000, 0.4907, 0.2130],
        [0.4603, 0.1386, 0.0277]])

In [90]:
b

tensor([[0.0000, 0.4907, 0.2130],
        [0.4603, 0.1386, 0.0277]])

In [91]:
id(a),id(b)

(139414591519744, 139414591519744)

In [92]:
b=a.clone()

In [94]:
a[0][0]=10
a,b

(tensor([[10.0000,  0.4907,  0.2130],
         [ 0.4603,  0.1386,  0.0277]]),
 tensor([[0.0000, 0.4907, 0.2130],
         [0.4603, 0.1386, 0.0277]]))

In [93]:
id(a),id(b)

(139414591519744, 139414591078800)

#  Tensor on GPU

In [95]:
torch.cuda.is_available()

True

In [96]:
device=torch.device('cuda')

In [97]:
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [100]:
b=a.to(device)
b

tensor([[10.0000,  0.4907,  0.2130],
        [ 0.4603,  0.1386,  0.0277]], device='cuda:0')

In [101]:
b+5

tensor([[15.0000,  5.4907,  5.2130],
        [ 5.4603,  5.1386,  5.0277]], device='cuda:0')

# Reshaping

In [104]:
a.reshape(3,2)

tensor([[10.0000,  0.4907],
        [ 0.2130,  0.4603],
        [ 0.1386,  0.0277]])

In [105]:
a.flatten()

tensor([10.0000,  0.4907,  0.2130,  0.4603,  0.1386,  0.0277])

In [106]:
b=torch.rand(2,3,4)
b

tensor([[[0.5662, 0.3503, 0.6555, 0.7667],
         [0.2269, 0.7555, 0.6458, 0.3673],
         [0.1770, 0.2966, 0.9925, 0.2103]],

        [[0.1292, 0.1719, 0.9127, 0.6818],
         [0.1953, 0.9991, 0.1133, 0.0135],
         [0.1450, 0.7819, 0.3134, 0.2983]]])

In [108]:
b.permute(2,0,1)
b.shape

torch.Size([2, 3, 4])

In [110]:
c=torch.rand(226,226,3)
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [113]:
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# Numpy and Torch

In [114]:
import numpy as np


In [118]:
b=a.numpy()
type(b),b

(numpy.ndarray,
 array([[10.        ,  0.49073827,  0.21299201],
        [ 0.46031797,  0.13861811,  0.02768636]], dtype=float32))

In [116]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [117]:
torch.from_numpy(c)

tensor([1, 2, 3])